#include "Renderer/VulkanCheck.h"

#include "Platform/Debugger.h"
#include "Viva/Log.h"

// Generated by Khronos and shipped with the SDK: turns enum values into their names, so a log
// says VK_ERROR_OUT_OF_DEVICE_MEMORY instead of -2. It's about 15,000 lines, which is why only
// this file includes it.
#include <vulkan/vk_enum_string_helper.h>

namespace Viva {

const char* VkResultName(VkResult result) { return string_VkResult(result); }
const char* VkFormatName(VkFormat format) { return string_VkFormat(format); }
const char* VkPresentModeName(VkPresentModeKHR mode) { return string_VkPresentModeKHR(mode); }
std::string VkMemoryPropertyNames(VkMemoryPropertyFlags flags) { return string_VkMemoryPropertyFlags(flags); }

namespace Detail {

void VulkanCallFailed(VkResult result, const char* call, std::source_location location)
{
    Log::Error("Vulkan call failed with {}: {}", VkResultName(result), call);
    Log::Error("    at {}:{}", location.file_name(), location.line());
    BreakIntoDebuggerOrExit();
}

} // namespace Detail

} // namespace Viva
